name: Build and push Docker image

env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    TAG: ${{ steps.date.outputs.date }}

on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - run: echo $TAG

      - name: Log in to Docker Hub
        uses: docker/login-action
        with:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:${{ env.tag }} .

      #- name: Push Docker image
      #  run: docker push ghcr.io/${{ github.repository }}:${{ env.tag }}