name: Build and push Docker image

on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:${{ steps.date.outputs.date }} .

      #- name: Push Docker image
      #  run: docker push ghcr.io/${{ github.repository }}:${{ steps.date.outputs.date }}