name: Build and push Docker image

env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    TAG: ${{ github.sha }}

on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - run: echo $TAG


      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:${{ env.tag }} .

      #- name: Push Docker image
      #  run: docker push ghcr.io/${{ github.repository }}:${{ env.tag }}